# Generated by Django 3.1.2 on 2020-11-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadmanstatusmodel',
            name='client',
        ),
        migrations.AddField(
            model_name='deadmanstatusmodel',
            name='client_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.DeleteModel(
            name='ClientModel',
        ),
    ]
